import "./globals.scss";
import { Roboto } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "700", "100", "900", "500"],
});

export const metadata = {
  title: "Slaysheet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider>
          <main>{children}</main>
        </ClerkProvider>
      </body>
    </html>
  );
}
